server:
  port: 7632

spring:
  #datasource:
    #url: jdbc:postgresql://localhost:5432/monitorservice
    #username: postgres
    #password: Sleuteltje123
    #driver-class-name: org.postgresql.Driver
  datasource:
    url: jdbc:postgresql://db-postgresql-lyriqu-cluster-do-user-8860308-0.b.db.ondigitalocean.com:25060/monitoring
    username: doadmin
    password: vksf33msdevjvrwq
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.lob.non_contextual-creation: true
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.us-east-2.amazonaws.com/us-east-2_V4yvtYUjY