/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_V4yvtYUjY",
    "aws_user_pools_web_client_id": "1a7cgpajt25rbs0edj45kochab",
    
};


export default awsmobile;
