apiVersion: apps/v1
kind: Deployment
metadata:
  name: lyriqu-music-prod
  namespace: music-service
  labels:
    app: lyriqu-music-prod
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: lyriqu-container-music-prod
  template:
    metadata:
      labels:
        app: lyriqu-container-music-prod
    spec:
      containers:
        - name: lyriqu-music-prod
          image: registry.gitlab.com/lyriqu/services/music-service:${CICD_GIT_COMMIT}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7630
      imagePullSecrets:
        - name: docker-registry
---
kind: Service
apiVersion: v1
metadata:
  name: lyriqu-music-service
  namespace: music-service
spec:
  selector:
    app: lyriqu-container-music-prod
  ports:
    - protocol: TCP
      port: 7630
      targetPort: 7630
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: lyriqu-music-ingress-prod
  namespace: music-service
spec:
  rules:
  - host: api.lyriqu.nl
    http:
      paths:
      - backend:
          serviceName: lyriqu-music-service
          servicePort: 7630
        path: /music
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - api.lyriqu.nl
    secretName: api-tls
